docs:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - docs/**
        - docs_src/**
      - all-globs-to-all-files:
        - '!asyncer/**'
        - '!pyproject.toml'

internal:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - .github/**
        - scripts/**
        - .gitignore
        - .pre-commit-config.yaml
        - uv.lock
      - all-globs-to-all-files:
        - '!docs/**'
        - '!asyncer/**'
        - '!pyproject.toml'
