site_name: Asyncer
site_description: Asyncer, async and await, focused on developer experience.
site_url: https://asyncer.tiangolo.com/
theme:
  name: material
  palette:
  - scheme: default
    primary: orange
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: orange
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: tiangolo/asyncer
repo_url: https://github.com/tiangolo/asyncer
edit_uri: ''
nav:
  - Asyncer: index.md
  - Tutorial - User Guide:
    - tutorial/index.md
    - tutorial/first-steps.md
    - tutorial/runnify.md
    - tutorial/soonify.md
    - tutorial/soonify-return.md
    - tutorial/asyncify.md
    - tutorial/syncify.md
    - tutorial/syncify-no-raise.md
  - help.md
  - release-notes.md
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- mdx_include

extra:
  analytics:
    provider: google
    property: UA-216293837-1
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/tiangolo/asyncer
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/tiangolo
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/tiangolo
  - icon: fontawesome/brands/dev
    link: https://dev.to/tiangolo
  - icon: fontawesome/brands/medium
    link: https://medium.com/@tiangolo
  - icon: fontawesome/solid/globe
    link: https://tiangolo.com

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js
