name: Latest Changes

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: 'false'

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # To allow latest-changes to commit to the main branch
          token: ${{ secrets.ASYNCER_LATEST_CHANGES }}
      # Allow debugging with tmate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
        with:
          limit-access-to-actor: true
      - uses: docker://tiangolo/latest-changes:0.1.1
      # - uses: tiangolo/latest-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: docs/release-notes.md
          latest_changes_header: '## Latest Changes'
          end_regex: '^## '
          debug_logs: true
          labels: >
            [
              {"label": "breaking", "header": "### Breaking Changes"},
              {"label": "security", "header": "### Security Fixes"},
              {"label": "feature", "header": "### Features"},
              {"label": "bug", "header": "### Fixes"},
              {"label": "refactor", "header": "### Refactors"},
              {"label": "upgrade", "header": "### Upgrades"},
              {"label": "docs", "header": "### Docs"},
              {"label": "lang-all", "header": "### Translations"},
              {"label": "internal", "header": "### Internal"}
            ]
          next_section_start: '^### '
